version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.6.1
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    restart: always
    volumes:
      - type: volume
        source: zkDataDir
        target: /data
      - type: volume
        source: zkDataLogDir
        target: /datalog

  # 暴露端口出去，只能启动一个实例
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka
      HOSTNAME_COMMAND: "ifconfig eth0 | awk '/inet addr/{print $$2}' | awk -F':' '{print $$NF}'"
    volumes:
      - type: volume
        source: kafka
        target: /kafka
    depends_on:
      - zookeeper

  es:
    image: elasticsearch:7.9.0
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    environment:
      discovery.type: single-node
    volumes:
      - type: volume
        source: es
        target: /var/lib/elasticsearch

  kibana:
    image: kibana:7.9.0
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200

volumes:
  zkDataDir:
  zkDataLogDir:
  kafka:
  es:
