version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.6.1
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    restart: always
    volumes:
      - type: volume
        source: zkDataDir
        target: /data
      - type: volume
        source: zkDataLogDir
        target: /datalog

  # 暴露端口出去，只能启动一个实例
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka
      HOSTNAME_COMMAND: "ifconfig eth0 | awk '/inet addr/{print $$2}' | awk -F':' '{print $$NF}'"
    volumes:
      - type: volume
        source: kafka
        target: /kafka
    depends_on:
      - zookeeper

  es:
    image: elasticsearch:7.9.0
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    environment:
      discovery.type: single-node
    volumes:
      - type: volume
        source: es
        target: /var/lib/elasticsearch

  kibana:
    image: kibana:7.9.0
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    depends_on:
      - es

  mysql:
    image: mysql:5.7
    command: --log-bin=mysql-bin --expire-logs-days=1 --server-id=123
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - type: volume
        source: mysql
        target: /var/lib/mysql

  debezium_connect:
    image: debezium/connect:1.3
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
        mode: host
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - zookeeper
      - kafka
      - mysql

  canal_connect:
    image: canal/canal-server:v1.1.4
    depends_on:
      - kafka
      - mysql

  clickhouse:
    image: yandex/clickhouse-server:20.8
    ports:
      - target: 8123
        published: 8123
        protocol: tcp
        mode: host
    #      - target: 9000
    #        published: 9000
    #        protocol: tcp
    #        mode: host
    volumes:
      - type: volume
        source: clickhouse
        target: /var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  clickhouse_client:
    image: yandex/clickhouse-client:20.8
    command: --host clickhouse
    stdin_open: true
    tty: true
    depends_on:
      - clickhouse
volumes:
  zkDataDir:
  zkDataLogDir:
  kafka:
  es:
  mysql:
  clickhouse:
