version: '3.7'

services:
  zookeeper:
    image: zookeeper
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    restart: always
    volumes:
      - type: volume
        source: zkDataDir
        target: /data
      - type: volume
        source: zkDataLogDir
        target: /datalog

  # 暴露端口出去，只能启动一个实例
  kafka:
    image: wurstmeister/kafka
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka
      HOSTNAME_COMMAND: "ifconfig eth0 | awk '/inet addr/{print $$2}' | awk -F':' '{print $$NF}'"
    volumes:
      - type: volume
        source: kafka
        target: /kafka
    depends_on:
      - zookeeper

volumes:
  zkDataDir:
  zkDataLogDir:
  kafka:
